/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.aptech.GUI;

import com.aptech.Session;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author MyPC
 */
public class AdminFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public AdminFrame() {
        initComponents();
        try {
            this.setIconImage(ImageIO.read(new File("images/favicon.png")));
        } catch (IOException ex) {
            System.out.println(ex.getMessage());
        }
        this.setTitle("Hello " + Session.fullName);
        jbAccount.doClick();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpMenu = new javax.swing.JPanel();
        jbAccount = new javax.swing.JButton();
        jbFir = new javax.swing.JButton();
        jpContain = new javax.swing.JPanel();
        jpAvartar = new javax.swing.JPanel();
        jlAvartar = new javax.swing.JLabel();
        jbUserInfo = new javax.swing.JButton();
        jpBanner = new javax.swing.JPanel();
        jlBanner = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemExit = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItemAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(806, 700));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpMenu.setBackground(new java.awt.Color(221, 221, 221));

        jbAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/account.png"))); // NOI18N
        jbAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAccountActionPerformed(evt);
            }
        });

        jbFir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/FIR.png"))); // NOI18N
        jbFir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpMenuLayout = new javax.swing.GroupLayout(jpMenu);
        jpMenu.setLayout(jpMenuLayout);
        jpMenuLayout.setHorizontalGroup(
            jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenuLayout.createSequentialGroup()
                .addGroup(jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jbFir, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jbAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 1, Short.MAX_VALUE))
        );
        jpMenuLayout.setVerticalGroup(
            jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbAccount)
                .addGap(48, 48, 48)
                .addComponent(jbFir, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(321, Short.MAX_VALUE))
        );

        getContentPane().add(jpMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 160, 500));

        jpContain.setMaximumSize(new java.awt.Dimension(600, 500));
        jpContain.setMinimumSize(new java.awt.Dimension(600, 500));
        jpContain.setPreferredSize(new java.awt.Dimension(600, 500));
        jpContain.setLayout(new java.awt.CardLayout());
        getContentPane().add(jpContain, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 940, -1));

        javax.swing.GroupLayout jpAvartarLayout = new javax.swing.GroupLayout(jpAvartar);
        jpAvartar.setLayout(jpAvartarLayout);
        jpAvartarLayout.setHorizontalGroup(
            jpAvartarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        jpAvartarLayout.setVerticalGroup(
            jpAvartarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        getContentPane().add(jpAvartar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 120, 120));
        getContentPane().add(jlAvartar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 120, 120));

        jbUserInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/briefcase_view.png"))); // NOI18N
        jbUserInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbUserInfoActionPerformed(evt);
            }
        });
        getContentPane().add(jbUserInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 30, -1));

        jpBanner.setBackground(new java.awt.Color(13, 200, 189));

        jlBanner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/banner.gif"))); // NOI18N

        javax.swing.GroupLayout jpBannerLayout = new javax.swing.GroupLayout(jpBanner);
        jpBanner.setLayout(jpBannerLayout);
        jpBannerLayout.setHorizontalGroup(
            jpBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlBanner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpBannerLayout.setVerticalGroup(
            jpBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlBanner, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );

        getContentPane().add(jpBanner, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 600, 120));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/UserFrameBackground.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 650));

        jMenu1.setText("File");
        jMenu1.add(jSeparator1);

        jMenuItemExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Error.png"))); // NOI18N
        jMenuItemExit.setText("Exit");
        jMenuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExitActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemExit);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Help");

        jMenuItemAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/about.png"))); // NOI18N
        jMenuItemAbout.setText("About");
        jMenuItemAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAboutActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemAbout);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExitActionPerformed
        int showConfirmDialog = JOptionPane.showConfirmDialog(null, "Are you sure want to exit?", "Confirm exit", JOptionPane.OK_CANCEL_OPTION);
        if (showConfirmDialog == JOptionPane.OK_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jMenuItemExitActionPerformed

    private void jMenuItemAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAboutActionPerformed
        JOptionPane.showMessageDialog(null, "Member:\n- Vu Thi Thanh Huyen\n- Truong Ba Nam\n- Do Viet Huy\n- Duong Ngoc Son", "About", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItemAboutActionPerformed

    private void jbUserInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbUserInfoActionPerformed
        UserInfo userInfo = new UserInfo();
        userInfo.setVisible(true);
    }//GEN-LAST:event_jbUserInfoActionPerformed

    private void jbAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAccountActionPerformed
        changeButtonImageOrginal();
        changeButtonImage(jbAccount, "images/Button/account-hover.png");
        AccountManagement accountManagement = new AccountManagement();
        changePanel(accountManagement);
    }//GEN-LAST:event_jbAccountActionPerformed

    private void jbFirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFirActionPerformed
        changeButtonImageOrginal();
        changeButtonImage(jbFir, "images/Button/FIR-HOVER.png");
    }//GEN-LAST:event_jbFirActionPerformed

    public void changeButtonImage(JButton button, String path) {
        Icon icon = new ImageIcon(path);
        button.setIcon(icon);
    }

    public void changeButtonImageOrginal() {
        changeButtonImage(jbAccount, "images/Button/account.png");
        changeButtonImage(jbFir, "images/Button/FIR.png");

    }

    public void changePanel(JPanel panel) {
        jpContain.removeAll();
        jpContain.repaint();
        jpContain.revalidate();
        jpContain.add(panel);
        jpContain.repaint();
        jpContain.revalidate();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemAbout;
    private javax.swing.JMenuItem jMenuItemExit;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JButton jbAccount;
    private javax.swing.JButton jbFir;
    private javax.swing.JButton jbUserInfo;
    private javax.swing.JLabel jlAvartar;
    private javax.swing.JLabel jlBanner;
    private javax.swing.JPanel jpAvartar;
    private javax.swing.JPanel jpBanner;
    private javax.swing.JPanel jpContain;
    private javax.swing.JPanel jpMenu;
    // End of variables declaration//GEN-END:variables
}
