/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.aptech.GUI;

import com.aptech.Session;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author MyPC
 */
public class UserFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public UserFrame() {
        initComponents();
        try {
            this.setIconImage(ImageIO.read(new File("images/favicon.png")));
        } catch (IOException ex) {
            System.out.println(ex.getMessage());
        }
        this.setTitle("Hello "+Session.fullName);
        jbCaseHistory.doClick();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpMenu = new javax.swing.JPanel();
        jbCaseHistory = new javax.swing.JButton();
        jbComplaint = new javax.swing.JButton();
        jbCriminal = new javax.swing.JButton();
        jbPostmortem = new javax.swing.JButton();
        jbPrisoners = new javax.swing.JButton();
        jbMostWanted = new javax.swing.JButton();
        jpFunction = new javax.swing.JPanel();
        jpAvartar = new javax.swing.JPanel();
        jlAvartar = new javax.swing.JLabel();
        jbUserInfo = new javax.swing.JButton();
        jpBanner = new javax.swing.JPanel();
        jlBanner = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemExit = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItemAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(806, 700));
        setMinimumSize(new java.awt.Dimension(806, 700));
        setPreferredSize(new java.awt.Dimension(806, 700));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpMenu.setBackground(new java.awt.Color(221, 221, 221));

        jbCaseHistory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CASE-HISTORY.png"))); // NOI18N
        jbCaseHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCaseHistoryActionPerformed(evt);
            }
        });

        jbComplaint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/COMPALINT.png"))); // NOI18N
        jbComplaint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbComplaintActionPerformed(evt);
            }
        });

        jbCriminal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CRIMINAL.png"))); // NOI18N
        jbCriminal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCriminalActionPerformed(evt);
            }
        });

        jbPostmortem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/POSTMORTEM.png"))); // NOI18N
        jbPostmortem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPostmortemActionPerformed(evt);
            }
        });

        jbPrisoners.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/PRISONER.png"))); // NOI18N
        jbPrisoners.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPrisonersActionPerformed(evt);
            }
        });

        jbMostWanted.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/WANTED.png"))); // NOI18N
        jbMostWanted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMostWantedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpMenuLayout = new javax.swing.GroupLayout(jpMenu);
        jpMenu.setLayout(jpMenuLayout);
        jpMenuLayout.setHorizontalGroup(
            jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenuLayout.createSequentialGroup()
                .addGroup(jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jbPrisoners, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jbPostmortem, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jbCriminal, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jbComplaint, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jbCaseHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 1, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpMenuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jbMostWanted, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpMenuLayout.setVerticalGroup(
            jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbCaseHistory)
                .addGap(18, 18, 18)
                .addComponent(jbComplaint)
                .addGap(18, 18, 18)
                .addComponent(jbCriminal)
                .addGap(31, 31, 31)
                .addComponent(jbPostmortem)
                .addGap(26, 26, 26)
                .addComponent(jbPrisoners)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jbMostWanted, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jpMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 160, 500));

        jpFunction.setMaximumSize(new java.awt.Dimension(600, 500));
        jpFunction.setMinimumSize(new java.awt.Dimension(600, 500));
        jpFunction.setPreferredSize(new java.awt.Dimension(600, 500));

        javax.swing.GroupLayout jpFunctionLayout = new javax.swing.GroupLayout(jpFunction);
        jpFunction.setLayout(jpFunctionLayout);
        jpFunctionLayout.setHorizontalGroup(
            jpFunctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        jpFunctionLayout.setVerticalGroup(
            jpFunctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        getContentPane().add(jpFunction, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, -1, -1));

        javax.swing.GroupLayout jpAvartarLayout = new javax.swing.GroupLayout(jpAvartar);
        jpAvartar.setLayout(jpAvartarLayout);
        jpAvartarLayout.setHorizontalGroup(
            jpAvartarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        jpAvartarLayout.setVerticalGroup(
            jpAvartarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        getContentPane().add(jpAvartar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 120, 120));
        getContentPane().add(jlAvartar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 120, 120));

        jbUserInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/briefcase_view.png"))); // NOI18N
        jbUserInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbUserInfoActionPerformed(evt);
            }
        });
        getContentPane().add(jbUserInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 30, -1));

        jpBanner.setBackground(new java.awt.Color(13, 200, 189));

        jlBanner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/banner.gif"))); // NOI18N

        javax.swing.GroupLayout jpBannerLayout = new javax.swing.GroupLayout(jpBanner);
        jpBanner.setLayout(jpBannerLayout);
        jpBannerLayout.setHorizontalGroup(
            jpBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlBanner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpBannerLayout.setVerticalGroup(
            jpBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlBanner, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );

        getContentPane().add(jpBanner, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 600, 120));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/UserFrameBackground.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 650));

        jMenu1.setText("File");
        jMenu1.add(jSeparator1);

        jMenuItemExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Error.png"))); // NOI18N
        jMenuItemExit.setText("Exit");
        jMenuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExitActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemExit);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Help");

        jMenuItemAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/about.png"))); // NOI18N
        jMenuItemAbout.setText("About");
        jMenuItemAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAboutActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemAbout);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbCaseHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCaseHistoryActionPerformed
        changeButtonImageOrginal();
        changeButtonImage(jbCaseHistory, "images/Button/CASE-HISTORY-HOVER.png");
    }//GEN-LAST:event_jbCaseHistoryActionPerformed

    private void jbComplaintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbComplaintActionPerformed
        changeButtonImageOrginal();
        changeButtonImage(jbComplaint, "images/Button/COMPLAINT-HOVER.png");
    }//GEN-LAST:event_jbComplaintActionPerformed

    private void jbCriminalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCriminalActionPerformed
        changeButtonImageOrginal();
        changeButtonImage(jbCriminal, "images/Button/CRIMINAL-HOVER.png");
    }//GEN-LAST:event_jbCriminalActionPerformed

    private void jbPostmortemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPostmortemActionPerformed
        changeButtonImageOrginal();
        changeButtonImage(jbPostmortem, "images/Button/POSTMORTEM-HOVER.png");
    }//GEN-LAST:event_jbPostmortemActionPerformed

    private void jbPrisonersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPrisonersActionPerformed
        changeButtonImageOrginal();
        changeButtonImage(jbPrisoners, "images/Button/PRISONER-HOVER.png");
    }//GEN-LAST:event_jbPrisonersActionPerformed

    private void jbMostWantedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMostWantedActionPerformed
        changeButtonImageOrginal();
        changeButtonImage(jbMostWanted, "images/Button/WANTED-HOVER.png");
    }//GEN-LAST:event_jbMostWantedActionPerformed

    private void jMenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExitActionPerformed
        int showConfirmDialog = JOptionPane.showConfirmDialog(null, "Are you sure want to exit?", "Confirm exit", JOptionPane.OK_CANCEL_OPTION);
        if (showConfirmDialog == JOptionPane.OK_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jMenuItemExitActionPerformed

    private void jMenuItemAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAboutActionPerformed
       JOptionPane.showMessageDialog(null, "Member:\n- Vu Thi Thanh Huyen\n- Truong Ba Nam\n- Do Viet Huy\n- Duong Ngoc Son", "About", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItemAboutActionPerformed

    private void jbUserInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbUserInfoActionPerformed
        UserInfo userInfo = new UserInfo();
        userInfo.setVisible(true);
    }//GEN-LAST:event_jbUserInfoActionPerformed

    public void changeButtonImage(JButton button, String path) {
        Icon icon = new ImageIcon(path);
        button.setIcon(icon);
    }

    public void changeButtonImageOrginal() {
        changeButtonImage(jbCaseHistory, "images/Button/CASE-HISTORY.png");
        changeButtonImage(jbComplaint, "images/Button/COMPALINT.png");
        changeButtonImage(jbCriminal, "images/Button/CRIMINAL.png");
        changeButtonImage(jbPostmortem, "images/Button/POSTMORTEM.png");
        changeButtonImage(jbPrisoners, "images/Button/PRISONER.png");
        changeButtonImage(jbMostWanted, "images/Button/WANTED.png");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemAbout;
    private javax.swing.JMenuItem jMenuItemExit;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JButton jbCaseHistory;
    private javax.swing.JButton jbComplaint;
    private javax.swing.JButton jbCriminal;
    private javax.swing.JButton jbMostWanted;
    private javax.swing.JButton jbPostmortem;
    private javax.swing.JButton jbPrisoners;
    private javax.swing.JButton jbUserInfo;
    private javax.swing.JLabel jlAvartar;
    private javax.swing.JLabel jlBanner;
    private javax.swing.JPanel jpAvartar;
    private javax.swing.JPanel jpBanner;
    private javax.swing.JPanel jpFunction;
    private javax.swing.JPanel jpMenu;
    // End of variables declaration//GEN-END:variables
}
